### ISSUE TITLE
Feature Request: Set TTL on keys when saved into Redis

### ISSUE THREAD

**Issue by nyanbinaryneko** [e271828-/event-reporter#1]
**Is your feature request related to a problem? Please describe.**
Set optional TTL values on save for an event

**Describe the solution you'd like**
Allow the user to set a TTL via an optional environment variable. if the env var is set, when the key and data are saved, the TTL for the key will be set. This will keep the redis cache small as keys are expired.

**Comment by e271828-** [comment]
https://github.com/e271828-/event-reporter/pull/2
